### PR TITLE
Change the modules to use lncm's fork

### PR DESCRIPTION
**Pull request by nolim1t**
Change the modules to use LNCM's fork

### CODE REVIEW

**Comment by meeDamian** [comment]
Have you actually tested this one works as well?

The reason I haven't merged it in yet, is because I didn't have time to replace `pi-init2` and make sure it works the same.

**Comment by meeDamian** [comment]
Also, I think there might be some `Makefile` changes needed, but I don't recall the exact changes I've done to `pi-init3`

**Comment by nolim1t** [comment]
Yes I'm using it

**Comment by meeDamian** [comment]
I just had a moment to look a bit deeper into this PR, and this change doesn't affect the actual process at all, and doesn't cause `pi-init3` to be used. So if it worked, it worked because `pi-init2` worked :).

To make sure it works, some extra changes in Makefile are also necessary, you can either try your luck with that, or I'll be on it probably around tomorrow.

**Comment by meeDamian** [comment]
Closing in favour of #14

**Pull request closed without merging**
